### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by florencebriton** [flr/ss3om#2]
When I trying installing the package with the command :  devtools::install_github("iagomosqueira/ss3om")

I get the following error message:

√  checking for file 'C:\Users\BRI281\AppData\Local\Temp\Rtmpai6Hgz\remotes299015cff44\iagomosqueira-ss3om-27a72be/DESCRIPTION' ...
-  preparing 'ss3om': (754ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'ss3om/docs'
-  building 'ss3om_0.3.4.tar.gz'
   
* installing *source* package 'ss3om' ...
** R
** exec
** inst
** byte-compile and prepare package for lazy loading
Error : (converted from warning) package 'FLCore' was built under R version 3.5.3
ERROR: lazy loading failed for package 'ss3om'
* removing 'C:/Programs/R-3.5.2/library/ss3om'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/BRI281/AppData/Local/Temp/Rtmpai6Hgz/file2990282f258/ss3om_0.3.4.tar.gz’ had non-zero exit status

**Comment by iagomosqueira** [comment]
The warning refers to FLCore for R 3.6 in windows being at the moment a copy of the 3.5 package, will be updated soon. You can avoid the warning becoming an error by running

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
```

before calling `install_github`.
