### ISSUE TITLE
readFLSss3 gives wrong output when using a model with WAA

### ISSUE THREAD

**Issue by aleorio** [flr/ss3om#3]
Hi,

I have tried to use readFLSss3 on my SS3 model with WAA and I have found some inconsistencies.

I am using in my assessment the weight at age file and in my catch.wt of the FLStock I have a matrix filled with only the values of 2018 (last year) instead of the time varying weights.
This is also probably way the catches are wrong (because they are calculated as a SoP).
The maturity quant is also empty (also because of me using the weigth at aage file in ss I guess).
And the f of my last two ages (11 and 12) look wrong.

Best,

Ale

**Comment by iagomosqueira** [comment]
Hi. Could you probably check the lastest version? Some changes were made that could affect this.

Otherwise please make the files available again and I will look at fixing it.

**Comment by aleorio** [comment]
Hi Iago, 
Sorry but now I can't seem to be able to install the library in my computer...
library(devtools)
options(devtools.install.args = "--no-multiarch")
devtools::install_github("iagomosqueira/ss3om")

This gives me an error regarding FLCore

* installing *source* package 'ss3om' ...
** using staged installation
** R
** exec
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'FLCore' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'ss3om'
* removing 'C:/Program Files/R/R-3.6.0/library/ss3om'
Error: Failed to install 'ss3om' from GitHub:
  (converted from warning) installation of package ‘C:/Users/alor0001/AppData/Local/Temp/RtmpiOStVR/file39e0479e5bf7/ss3om_0.3.5.tar.gz’ had non-zero exit status

**Comment by iagomosqueira** [comment]
Hi,

Try calling this before devtools

```
 Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="TRUE")
```

to avoid a warning in FLCore being turned into an error. It has to do with the %*% method clashing with ggplot2.

**Comment by aleorio** [comment]
Sorry, still having problems... now with FLash I think.

* installing *source* package 'ss3om' ...
** using staged installation
** R
** exec
** inst
** byte-compile and prepare package for lazy loading
Warning messages:
1: package 'FLCore' was built under R version 3.6.1 
2: package 'iterators' was built under R version 3.6.1 
3: package 'FLFishery' was built under R version 3.6.1 
4: replacing previous import 'ggplot2::%+%' by 'FLCore::%+%' when loading 'ggplotFL' 
Warning: no function found corresponding to methods exports from 'mse' for: 'refpts<-'
** help
*** installing help indices
  converting help for package 'ss3om'
    finding HTML links ... done
    nameGrid                                html  
    readFLIBss3                             html  
    finding level-2 HTML links ... done

    readFLSRss3                             html  
    readFLSss3                              html  
    ss3slot                                 html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Warning: package 'FLCore' was built under R version 3.6.1
Warning: package 'iterators' was built under R version 3.6.1
Warning: package 'FLFishery' was built under R version 3.6.1
Warning: replacing previous import 'ggplot2::%+%' by 'FLCore::%+%' when loading 'ggplotFL'
Error: package or namespace load failed for 'ss3om' in library.dynam(lib, package, package.lib):
 DLL 'FLash' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
Warning: package 'FLCore' was built under R version 3.6.1
Warning: package 'iterators' was built under R version 3.6.1
Warning: package 'FLFishery' was built under R version 3.6.1
Warning: replacing previous import 'ggplot2::%+%' by 'FLCore::%+%' when loading 'ggplotFL'
Warning: no function found corresponding to methods exports from 'mse' for: 'refpts<-'
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-3.6.0/library/ss3om'

**Comment by iagomosqueira** [comment]
It is trying to install for 32 bits. Can you try with

```
devtools::install_github("flr/ss3om", INSTALL_opts=c("--no-multiarch"))
```
and see if now stays with 64 bit only?

**Comment by aleorio** [comment]
Now it works... but i thought I could switch the installation of the 32 bit outside like we did previously with options(devtools.install.args = "--no-multiarch")
Anyway, it doesn't seem to work. I still have the same problems as in the previous version. Here are the report and the CompReport files. Let me know if you need more and thanks for your help :)


[files.zip](https://github.com/flr/ss3om/files/3932577/files.zip)

**Comment by iagomosqueira** [comment]
readFLSss3 can now load mat and wt from wtatage.ss_new, pushed in b464235e3ea85bd01a2a8ab1ceda106230cd97d0.

Tested with only one stock, which has the same weight at age for all fleets.
