### ISSUE TITLE
Error in buildFLSss330 when loading forecast

### ISSUE THREAD

**Issue by ssanchezAZTI** [flr/ss3om#8]
Hi,

When calling buildFLSss330 with forecast argument equal to TRUE, I get an error as catches and discards have different dimensions.
It is due to the fact that the discards call does not include the era argument. Including it, the issue is solved.

discards <- ss3catch30(datage[Type == "disc",], wtatage, dmns, morphs, idx=idx, era=era)

Best,
Sonia

**Comment by iagomosqueira** [comment]
Thanks. fixed now in commit [ce9b50d06e0abea60967e69a586f4676a787dff4]
