### ISSUE TITLE
revise column names used in SS3 input files

### ISSUE THREAD

**Issue by iantaylor-NOAA** [flr/ss3om#9]
The r4ss package has just revised the column names used in the functions to read SS3 input files (see https://github.com/r4ss/r4ss/releases/tag/v1.50.0).
I notice that flr/ss3om depends on r4ss and uses the old name convention (e.g. in the section below):
https://github.com/flr/ss3om/blob/2b2b421ab313f133f613ad79987fe662ca417b87/R/build330.R#L752

So it's likely that the r4ss will break things in this package. Sorry for whatever trouble that causes.

Let me know if there are any questions or you want help on any changes.

**Comment by iagomosqueira** [comment]
Is this change only affecting the data frames loaded from the .dat file? Those returned by `SS_output` (e.g. `catage`) maintain the old column names, isn't it?

**Comment by iagomosqueira** [comment]
Changes made to s33om version 0.5.3 that now requires r4ss >= 1.50.0

**Comment by iantaylor-NOAA** [comment]
@iagomosqueira, yes the changes in SS3 and r4ss were only focused on the input files. Changing Report.sso and `r4ss::SS_output()` seemed too disruptive to the much larger set of existing code that depends on those things.

**Comment by iagomosqueira** [comment]
As far as I can see the latest commit has adapted ss3om to those changes. Thanks for raising the issue
